name: Test

on: pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
      - run: bun run build
      - name: Serve app
        env:
          PORT: 3000
        run: |
          bun run preview &
          sleep 1
          curl --fail --retry-connrefused --retry 3 http://localhost:3000
